version: '2'
services:
  # web server
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # app
      - ~/www:/var/www/
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # certificates
      - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
      - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
    links:
      - fpm:php-fpm-host

  # php-fpm
  fpm:
    build: ./php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ~/www:/var/www/
      # Your php.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    # environment:
      # Set your APP env variables here:
      # - APP_KEY=
      # - DB_HOST=
      # - DB_DATABASE=
      # - DB_USERNAME=
      # - DB_PASSWORD=
    links:
      - mysql:mysql-host
      - redis:redis-host

  # database
  mysql:
    image: mysql:5.7
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  # KV
  redis:
    image: redis:latest
    ports:
      # Allow client to access 6379
      - "6379:6379"
    volumes:
      # NOTE: your redis.conf will be stored in ./redis/redis.conf
      #- ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
